# GitHub Actions workflow for NextGenTorch CI

name: NextGenTorch CI

# Trigger the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow torch nextgentorch

    - name: Run tests
      run: |
        # Placeholder for future tests
        echo "Running tests for NextGenTorch"
        # Add actual test commands here when tests are implemented
        # For example: python -m unittest discover tests

    - name: Verify NextGenTorch model connectivity
      run: |
        python -c "
import tensorflow as tf
import torch
from nextgentorch.layers import DenseLayerWrapper

# Test with PyTorch
x_torch = torch.randn(1, 10)
dense_layer = DenseLayerWrapper(features=5)
y_torch = dense_layer(x_torch, target_framework='pytorch')
print('PyTorch output shape:', y_torch.shape)

# Test with TensorFlow
x_tf = tf.random.normal((1, 10))
y_tf = dense_layer(x_tf, target_framework='tensorflow')
print('TensorFlow output shape:', y_tf.shape)
        "

    - name: Report completion
      run: echo "NextGenTorch CI workflow completed successfully"
